# getting proper colors
export TERM="xterm-256color" 

# dotfiles
export DOTFILES="$HOME/.dotfiles"

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

[[ ! -d "${XDG_CONFIG_HOME}" ]] && mkdir -p "${XDG_CONFIG_HOME}"
[[ ! -d "${XDG_CACHE_HOME}" ]] && mkdir -p "${XDG_CACHE_HOME}"
[[ ! -d "${XDG_DATA_HOME}" ]] && mkdir -p "${XDG_DATA_HOME}" 

# editor
#export EDITOR="emacsclient -t -a ''" # in terminal
export EDITOR="nvim" # in terminal 
export VISUAL="emacsclient -c -a emacs" # GUI mode

# manpage most readable
#export MANPAGER="nvim -c 'set ft=man' -" # set neovim as manpager
export MANPAGER="sh -c 'col -bx | bat -l man -p'" # set bat as manpager

# paths
paths=(
  "$HOME/bin"
  "$HOME/.local/bin"
  "$DOTFILES/bin" 
)

for p in "${paths[@]}"; do
  if [[ -d $p ]]; then
    export PATH="$p:$PATH"
  fi
done

# set vi mode
bindkey -v

# load aliases
source "$DOTFILES/misc/aliases"

# load configs
configs=(
  "autocompletion"
  "history"
  "keybindings"
)

for config in "${configs[@]}"; do
  if [[ -f "$DOTFILES/zsh/lib/$config.zsh" ]]; then
    source "$DOTFILES/zsh/lib/$config.zsh"
  fi
done

# setting the starship prompt
eval "$(starship init zsh)"
