#
# ~/.bashrc

# getting proper colors
export TERM="xterm-256color"

# no duplicate entries
export HISTCONTROL=ignoredups:erasedups

# dotfiles
export DOTFILES="$HOME/.dotfiles"

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

[[ ! -d "${XDG_CONFIG_HOME}" ]] && mkdir -p "${XDG_CONFIG_HOME}"
[[ ! -d "${XDG_CACHE_HOME}" ]] && mkdir -p "${XDG_CACHE_HOME}"
[[ ! -d "${XDG_DATA_HOME}" ]] && mkdir -p "${XDG_DATA_HOME}"

# editor
export EDITOR="nvim" # in terminal
export VISUAL="nvim" # GUI mode

# manpage most readable
#export MANPAGER="nvim -c 'set ft=man' -" # set neovim as manpager
export MANPAGER="sh -c 'col -bx | bat -l man -p'" # set bat as manpager

# paths
paths=(
  "$HOME/bin"
  "$HOME/.local/bin"
  "$DOTFILES/bin"
)

for p in "${paths[@]}"; do
  if [[ -d $p ]]; then
    export PATH="$p:$PATH"
  fi
done

# set vi mode
set -o vi
bind -m vi-command 'Control-l: clear-screen'
bind -m vi-insert 'Control-l: clear-screen'

# load aliases
source "$DOTFILES/misc/aliases"

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# config
shopt -s autocd # change to named directory
shopt -s cdspell # autocorrects cd misspellings
shopt -s cmdhist # save multi-line commands in history as single line
shopt -s dotglob
shopt -s histappend # do not overwrite history
shopt -s expand_aliases # expand aliases
shopt -s checkwinsize # checks term size when bash regains control

# setting the starship prompt
eval "$(starship init bash)"
